# -*- coding: utf-8 -*-
"""IOT_project_Detection_of_Parkinson's_disease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdTHMshDcqzGnqVm02SLFepr3BLgl774
"""

import numpy as np
import pandas as pd
import os, sys
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from google.colab import files
uploadedfiles=files.upload()

import io
df= pd.read_csv('parkinsons.data')
df.head()

features=df.loc[:,df.columns!='status'].values[:,1:]
labels=df.loc[:,'status'].values

print(labels[labels==1].shape[0], labels[labels==0].shape[0])

scaler=MinMaxScaler((-1,1))
x=scaler.fit_transform(features)
y=labels

x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=7)

model=XGBClassifier()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print(y_pred)

print(accuracy_score(y_test, y_pred)*100)

"""Predicting if a person has Parkinson's Disease

"""

x=[122.400,	148.650,	113.819,	0.00968,	0.00008,	0.00465,	0.00696,	0.01394,	0.06134,	0.626,	0.03134,	0.04518,	0.04368,	0.09403,	0.01929,	19.085,	0.458359,	0.819521,	-4.075192,	0.335590,	2.486855,	0.368674]

y_2=model.predict(x)
print(y_2)

